### PR TITLE
I translated it for Turkish

### PR DESCRIPTION
**Pull request by SailorOnDaTea**
you better use at least UTF-8

### CODE REVIEW

**Comment by andreldm** [comment]
Hi SailorOnDaTea, thanks, I really appreciate.

Note that translations are handled on [Transifex](https://www.transifex.com/kissplayer/), so besides accepting your pull request, I've uploaded the .po file to there. Any further improvement to the translation should be made on Transifex, I guess it's easier and nicer than pull requests ;)

**Comment by SailorOnDaTea** [comment]
okay. that time it said "unauthorized" so I pushed here. I guess because i didnt have account there.( first time I see that site)

**Comment by SailorOnDaTea** [comment]
so uhm.. How can I enable it? It's not listed in settings...

**Comment by andreldm** [comment]
My bad, on linux all you need is to set the LANG environment variable, but for windows the options are hard coded, tonight I'll add it to settings =)

**Comment by SailorOnDaTea** [comment]
thanks!

**Comment by andreldm** [comment]
Done.
You might wait for a release, build it by yourself or ask me a snapshot if you can't wait or build ^^
Note that I changed the locale from `tr_TR` to `tr`, it was like that because someone asked this locale on transifex but never really translated.

**Comment by SailorOnDaTea** [comment]
I'm on win7x64. I tried to build, but msys gave some 404 errors while trying to fetch dependencies. and then scripts quit with some red lines. Then I can't get anything compiled :/ I would be happy if you release soon or make a build for me :+1: 
btw, tr or tr_TR doesn't really matter. I've never seen any program in Cypriot Turkish yet, I guess they also understand standard Turkish.

**Comment by andreldm** [comment]
Here you are: https://github.com/andreldm/kissplayer/releases/tag/v0.6.5-beta

**Comment by SailorOnDaTea** [comment]
So fast! Thanks again! :)

**Pull request merged**
